### PR TITLE
Add failing test case for `preload_associations_lazily` for relation with includes called

### PR DESCRIPTION
**Pull request by PikachuEXE**
This is actually for a potential bug I found and I don't know how to fix
Bug:
If `#includes` is called before `#preload_associations_lazily`, 
any association not mentioned in `includes` will not be loaded in a batch when called

See test case for 
```ruby
it "loads association of association automatically when `includes` called"
```

### CODE REVIEW

**Comment by DmitryTsepelev** [comment]
Thank you for catching that! I'll try to dig into it during the next few days

**Comment by DmitryTsepelev** [comment]
The problem is that when `includes` is called, Rails loads `users` association [as part of](https://github.com/rails/rails/blob/5-1-stable/activerecord/lib/active_record/relation.rb#L684) `posts` relation initialization. It means that when `users` relation is loaded, `preloads_associations_lazily?` returns `false` and context is not created. I wonder if we could somehow detect preloading and check if parent association can be lazily loaded (we could do it in the `Preloader`, but it only has an access to an `Array` of  `Post` models, not relation).

I guess we should add this issue to the README for now 🙂

**Comment by PikachuEXE** [comment]
Let's update the readme for now
Not an urgent issue for me (I just swap remove calls to `includes`)

**Comment by DmitryTsepelev** [comment]
I've added a line and mentioned this issue

**Comment by DmitryTsepelev** [comment]
Fixed by #48

**Pull request closed without merging**
