### PR TITLE
Support ruby 2.7.0

### PR DESCRIPTION
**Pull request by DmitryTsepelev**

### CODE REVIEW

**Comment by PikachuEXE** [comment]
Looks good except my eyes hurt reading warning caused by other gems

**Comment by DmitryTsepelev** [comment]
Thanks for the review! My plan is to wait for other gems to make sure all warnings disappear before merging

**Comment by PikachuEXE** [comment]
Is it possible to restart the build with latest gem dependencies to see if those warning messages are gone?
Especially since [rails `6.0.3` released with ruby 2.7 warning fixes](https://github.com/rails/rails/pull/37935#issuecomment-625617169)

**Comment by DmitryTsepelev** [comment]
@PikachuEXE, done ([example](https://travis-ci.org/github/DmitryTsepelev/ar_lazy_preload/jobs/635153141)), looks like most of warnings are gone

**Comment by PikachuEXE** [comment]
Seems good for rails 6.0 & master
I guess this can be merged?

**Pull request merged**
